name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          install: true

      - name: Check version consistency
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          CARGO_VERSION=$(cargo metadata --no-deps --format-version=1 | jq '.packages[0].version' -r)
          AVIUTL2_VERSION=$(python -c 'import tomllib; print(tomllib.load(open("aviutl2.toml","rb"))["project"]["version"])')

          echo "Tag:     $TAG_VERSION"
          echo "Cargo:   $CARGO_VERSION"
          echo "aviutl2: $AVIUTL2_VERSION"

          test "$TAG_VERSION" = "$CARGO_VERSION"
          test "$TAG_VERSION" = "$AVIUTL2_VERSION"

      - name: Generate THIRD-PARTY-LICENSES
        run: mise run license:third-party

      - name: Build and Package au2pkg
        run: au2 release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./release/Karoterra.WaveformPreview-v*.au2pkg.zip
            ./release/catalog.json
